export default {
	pages: [
		'pages/home/index',
		'pages/badge/index',
		'pages/button/index',
		'pages/canvas/index',
		'pages/cell/index',
		'pages/custom-header/index',
		'pages/dropdown-menu/index',
		'pages/field/index',
		'pages/footer-button/index',
		'pages/form/index',
		'pages/icon/index',
		'pages/image/index',
		'pages/image-text-item/index',
		'pages/input-number/index',
		'pages/loading/index',
		'pages/media/index',
		'pages/modal/index',
		'pages/overlay/index',
		'pages/popup/index',
		'pages/price/index',
		'pages/progress/index',
		'pages/progress-circle/index',
		'pages/rate/index',
		'pages/result/index',
		'pages/search/index',
		'pages/skeleton/index',
		'pages/sort/index',
		'pages/tab/index',
		'pages/tab-pane/index',
		'pages/time-picker/index',
		'pages/toast/index',
		'pages/upload/index',
],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'Taro UI',
    navigationBarTextStyle: 'black'
  }
}
