export { default as SlLoading } from './components/sl-loading'
export { default as SlUpload } from './components/sl-upload'
export { default as SlImage } from './components/sl-image'
export { default as SlPrice } from './components/sl-price'
export { default as SlModal } from './components/sl-modal'
export { default as SlToast } from './components/sl-toast'
export { default as SlBadge } from './components/sl-badge'
export { default as SlOverlay } from './components/sl-overlay'
export { default as SlCustomHeader } from './components/sl-custom-header'
export { default as SlIcon } from './components/sl-icon'
export { default as SlPopup } from './components/sl-popup'

export { default as SlSkeleton } from './components/sl-skeleton'
export { default as SlCanvas } from './components/sl-canvas'